import os
import re
import base64
from dotenv import load_dotenv

load_dotenv()

from e2b_code_interpreter import Sandbox
from Backend.app.src.graph.state import GraphState
from Backend.app.src.graph.state_utils import require_state
from Backend.app.src.logs.logger import logger


def executor_node(state: GraphState) -> GraphState:
    """
    Execute the Python code generated by the Programmer Agent securely in an E2B Cloud Sandbox.
    """
    logger.info("Executor started: Routing to E2B Sandbox.")

    code = require_state(state, "generated_code")
    dataset_path = state.get("dataset_path")

    if not code.strip():
        return {
            "execution_status": "failed",
            "execution_error": "Programmer generated no code.",
            "execution_output": "",
        }

    artifact_dir = os.environ.get("LANGGRAPH_ARTIFACTS_DIR", "charts")
    os.makedirs(artifact_dir, exist_ok=True)

    # Remove markdown fences in case the AI generated them
    code = re.sub(r"```python|```", "", code)

    # Use /tmp directory inside the sandbox where write permissions are always granted
    dataset_filename = os.path.basename(dataset_path) if dataset_path else "dataset.csv"
    sandbox_dataset_path = f"/tmp/{dataset_filename}"

    try:
        # 1. Initialize the secure E2B cloud sandbox
        with Sandbox.create() as sandbox:

            # 2. Upload the local dataset directly to /tmp
            if dataset_path and os.path.exists(dataset_path):
                with open(dataset_path, "rb") as f:
                    sandbox.files.write(sandbox_dataset_path, f.read())

                # 3. Prepend setup block with global variables pre-loaded
                setup_code = (
                    f"global_df_path = '{sandbox_dataset_path}'\n"
                    "import pandas as pd\n"
                    "import numpy as np\n"
                    "import matplotlib.pyplot as plt\n"
                    "import seaborn as sns\n"
                    "import plotly.express as px\n"
                    "import plotly.graph_objects as go\n"
                    "global_df = pd.read_csv(global_df_path)\n"
                    "df = global_df\n"
                )
            else:
                setup_code = ""

            final_code = setup_code + code

            # 4. Execute the Python code in the isolated cloud environment
            execution = sandbox.run_code(final_code)

            # 5. Handle Execution Errors returned from E2B
            if execution.error:
                error_msg = f"{execution.error.name}: {execution.error.value}"
                logger.error(f"E2B Execution Error: {error_msg}")
                return {
                    "execution_status": "failed",
                    "execution_error": error_msg,
                    "execution_output": execution.text or "",
                    "chart_files": [],
                }

            # 6. Extract Outputs and Charts natively from E2B's execution results
            chart_files = []

            for i, result in enumerate(execution.results):
                # Save standard PNG charts (matplotlib/seaborn)
                if result.png:
                    chart_filename = f"chart_{i}.png"
                    chart_path = os.path.join(artifact_dir, chart_filename)
                    with open(chart_path, "wb") as f:
                        f.write(base64.b64decode(result.png))
                    chart_files.append(chart_filename)

                # Save interactive HTML charts (Plotly)
                elif result.html:
                    chart_filename = f"chart_{i}.html"
                    chart_path = os.path.join(artifact_dir, chart_filename)
                    with open(chart_path, "w", encoding="utf-8") as f:
                        f.write(result.html)
                    chart_files.append(chart_filename)

            logger.info("Execution completed successfully via E2B.")

            return {
                "execution_status": "success",
                "execution_output": execution.text.strip() if execution.text else "",
                "execution_error": "",
                "chart_files": chart_files,
                "executor_metrics": {
                    "charts": len(chart_files),
                    "success": True,
                },
            }

    except Exception as exc:
        logger.exception("E2B Sandbox connection or execution failed.")
        return {
            "execution_status": "failed",
            "execution_error": str(exc),
            "execution_output": "",
            "chart_files": [],
        }