import io
import os
import re
import sys

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import polars as pl
import seaborn as sns

from data_frame import load_dataframe
from src.graph.state import GraphState
from src.graph.state_utils import require_state
from src.logs.logger import logger
from src.tools.safe_execution import (
    SAFE_BUILTINS,
    normalize_visualization_artifacts,
    validate_analysis_code,
)

plt.switch_backend("Agg")


def executor_node(state: GraphState) -> GraphState:
    """
    Execute the Python code generated by the Programmer Agent.
    """

    logger.info("Executor started.")

    code = require_state(state, "generated_code")

    if not code.strip():
        return {
            "execution_status": "failed",
            "execution_error": "Programmer generated no code.",
            "execution_output": "",
        }

    artifact_dir = os.environ.get("LANGGRAPH_ARTIFACTS_DIR", "charts")
    os.makedirs(artifact_dir, exist_ok=True)

    # Remove markdown fences
    code = re.sub(r"```python|```", "", code)

    # Remove imports generated by the model
    code = re.sub(
        r"^\s*(?:from\s+\S+\s+import\s+.+|import\s+.+)\s*$",
        "",
        code,
        flags=re.MULTILINE,
    )

    # Remove interactive plotting
    code = re.sub(r"^\s*plt\.show\(\)\s*$", "", code, flags=re.MULTILINE)
    code = re.sub(r"^\s*fig\.show\(\)\s*$", "", code, flags=re.MULTILINE)

    # Rewrite chart save paths
    code = normalize_visualization_artifacts(code, artifact_dir)

    stdout = io.StringIO()
    old_stdout = sys.stdout
    sys.stdout = stdout

    try:
        exec_globals = {
            "__builtins__": SAFE_BUILTINS,
            "global_df": load_dataframe(),
            "pd": pd,
            "np": np,
            "pl": pl,
            "plt": plt,
            "sns": sns,
            "px": px,
            "go": go,
            "make_subplots": make_subplots,
        }

        compiled = compile(
            validate_analysis_code(code, artifact_dir=artifact_dir),
            "<generated-code>",
            "exec",
        )

        exec(compiled, exec_globals)

    except Exception as exc:

        logger.exception("Execution failed.")

        sys.stdout = old_stdout

        return {
            "execution_status": "failed",
            "execution_error": str(exc),
            "execution_output": stdout.getvalue(),
            "chart_files": [],
        }

    finally:
        sys.stdout = old_stdout

    chart_files = [
        os.path.join(artifact_dir, f).replace("\\", "/")
        for f in os.listdir(artifact_dir)
    ]

    logger.info("Execution completed successfully.")

    return {
        "execution_status": "success",
        "execution_output": stdout.getvalue(),
        "execution_error": "",
        "chart_files": chart_files,
    }