import re
from src.config import llm
from src.graph.state import GraphState
from langchain_core.messages import HumanMessage,SystemMessage

def reporter_node(state: GraphState):
    print("📝 Reporter is formatting the output...")
    
    # Give the Reporter the actual numbers generated by the Executor!
    user_prompt = (
        f"The Data Engineer just executed the code. Here are the raw logs and data:\n\n"
        f"{state.get('execution_output', 'No data output.')}\n\n"
        "Write the final Markdown report based ONLY on these numbers. "
        "Do not write generic definitions. "
        "If the logs mention that plots were saved (e.g., 'saved to sales_bar.png'), embed them in your report."
    )
    
    # Grab existing history and append our new prompt
    messages_to_send = state.get("messages", []) + [HumanMessage(content=user_prompt)]
    
    # Assuming you have a reporter_llm setup
    response = llm.invoke(messages_to_send)
    
    return {"final_report": response.content}