"""
quality.py

Pydantic models representing the output of the
Data Quality Assessment node.

The Quality Assessment node performs deterministic analysis
on the dataset and produces a structured report describing
data quality issues. This report is consumed by the
Supervisor and Cleaning Agent.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class Severity(str, Enum):
    """Severity level of a detected issue."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class MissingValueInfo(BaseModel):
    """
    Missing value statistics for a column.
    """

    model_config = ConfigDict(extra="forbid")

    column: str

    missing_count: int = Field(..., ge=0)

    missing_percentage: float = Field(..., ge=0.0, le=100.0)


class DuplicateInfo(BaseModel):
    """
    Duplicate statistics.
    """

    model_config = ConfigDict(extra="forbid")

    duplicate_rows: int = Field(..., ge=0)

    duplicate_percentage: float = Field(..., ge=0.0, le=100.0)


class OutlierInfo(BaseModel):
    """
    Outlier information for a numeric column.
    """

    model_config = ConfigDict(extra="forbid")

    column: str

    outlier_count: int = Field(..., ge=0)

    outlier_percentage: float = Field(..., ge=0.0, le=100.0)

    method: str = Field(
        default="IQR",
        description="Detection method used."
    )


class ConstantColumnInfo(BaseModel):
    """
    Column containing only one unique value.
    """

    model_config = ConfigDict(extra="forbid")

    column: str

    unique_value: str


class HighCardinalityInfo(BaseModel):
    """
    Categorical column having many unique values.
    """

    model_config = ConfigDict(extra="forbid")

    column: str

    unique_values: int

    unique_percentage: float = Field(..., ge=0.0, le=100.0)


class InvalidDtypeInfo(BaseModel):
    """
    Column whose detected datatype is likely incorrect.
    """

    model_config = ConfigDict(extra="forbid")

    column: str

    current_dtype: str

    suggested_dtype: str

    reason: str


class QualityIssue(BaseModel):
    """
    Generic issue detected during quality assessment.
    """

    model_config = ConfigDict(extra="forbid")

    severity: Severity

    title: str

    description: str

    recommendation: str


class CleaningRecommendation(BaseModel):
    """
    Recommended cleaning action.

    These recommendations will later be used by the
    Cleaning Agent when deciding which tools to call.
    """

    model_config = ConfigDict(extra="forbid")

    priority: int = Field(..., ge=1, le=5)

    action: str

    reason: str


class DataQualityReport(BaseModel):
    """
    Structured report generated by the
    Data Quality Assessment node.
    """

    model_config = ConfigDict(extra="forbid")

    quality_score: float = Field(
        ...,
        ge=0.0,
        le=100.0,
        description="Overall data quality score."
    )

    missing_values: List[MissingValueInfo] = Field(
        default_factory=list
    )

    duplicate_info: DuplicateInfo

    outliers: List[OutlierInfo] = Field(
        default_factory=list
    )

    constant_columns: List[ConstantColumnInfo] = Field(
        default_factory=list
    )

    high_cardinality_columns: List[HighCardinalityInfo] = Field(
        default_factory=list
    )

    invalid_dtypes: List[InvalidDtypeInfo] = Field(
        default_factory=list
    )

    issues: List[QualityIssue] = Field(
        default_factory=list
    )

    cleaning_recommendations: List[CleaningRecommendation] = Field(
        default_factory=list
    )

    summary: str

    execution_time: float = Field(
        default=0.0,
        ge=0.0
    )

    notes: Optional[str] = None