import io
import json
import re
import sys
from typing import Any

from src.logs.logger import logger
from src.tools.safe_execution import (
    SAFE_BUILTINS,
    validate_analysis_code,
)


def extract_python_code(llm_output: str) -> str:
    """
    Extract a Python code block from an LLM response.
    """

    match = re.search(
        r"```python\s*(.*?)```",
        llm_output,
        re.DOTALL,
    )

    code = match.group(1) if match else llm_output

    # Remove imports generated by the model
    code = re.sub(
        r"^\s*(?:from\s+\S+\s+import\s+.+|import\s+.+)\s*$",
        "",
        code,
        flags=re.MULTILINE,
    )

    # Prevent blocking execution
    code = re.sub(
        r"^\s*(?:plt|fig)\.show\(\)\s*$",
        "",
        code,
        flags=re.MULTILINE,
    )

    return code.strip()


def execute_generated_code(
    *,
    code: str,
    exec_globals: dict[str, Any],
    artifact_dir: str | None = None,
    task_name: str = "generated-code",
) -> dict:
    """
    Validate and execute generated Python code.

    Returns

    {
        status,
        output,
        code,
        error
    }
    """

    stdout = io.StringIO()
    old_stdout = sys.stdout

    try:

        sys.stdout = stdout

        compiled = compile(
            validate_analysis_code(
                code,
                artifact_dir=artifact_dir,
            ),
            f"<{task_name}>",
            "exec",
        )

        exec(
            compiled,
            {
                "__builtins__": SAFE_BUILTINS,
                **exec_globals,
            },
        )

        logger.info("%s executed successfully.", task_name)

        return {
            "status": "success",
            "output": stdout.getvalue(),
            "code": code,
            "error": None,
        }

    except Exception as exc:

        logger.exception("%s execution failed.", task_name)

        return {
            "status": "failed",
            "output": stdout.getvalue(),
            "code": code,
            "error": str(exc),
        }

    finally:
        sys.stdout = old_stdout


def execute_llm_code(
    *,
    llm_output: str,
    exec_globals: dict[str, Any],
    artifact_dir: str | None = None,
    task_name: str,
) -> dict:
    """
    Convenience wrapper:

    LLM Output
        ↓
    Extract Code
        ↓
    Validate
        ↓
    Execute
        ↓
    Return structured result
    """

    code = extract_python_code(llm_output)

    return execute_generated_code(
        code=code,
        exec_globals=exec_globals,
        artifact_dir=artifact_dir,
        task_name=task_name,
    )


def to_json(result: dict) -> str:
    """
    Serialize execution result.
    """

    return json.dumps(result)